active_profile = "keepassxc"
browser_type = "firefox"
nr_threads = 10  #optional default: 1

[profile.keepassxc]
type = "kdbx"
sources = [ "private-kdbxc" ]

[[sources]]
name = "private-kdbxc"
file = "tests/resources/test_db.kdbx"
blocklist = [ "chess.com", "github.com", "lichess.org",  ]    #optional

[profile.keepassx]
type = "kdbx"
sources = [ "private-kdbx" ]

[[sources]]
name = "private-kdbx"
file = "tests/resources/kepassx.kdbx"
blocklist = [ "chess.com", "github.com" ]

[profile.keepass]
type = "kdbx"
sources = [ "private-kdb" ]

[[sources]]
name = "private-kdb"
file = "tests/resources/keepass.kdbx"
blocklist = [ "chess.com", "github.com" ]

[profile.work-pass]
type = "pass"
sources = [ "work-pass" ]   #optional

[profile.pwsafe]
type = "pwsafe"
sources = [ "pwsafe" ]

[[sources]]
name = "pwsafe"
file = "tests/resources/pwsafe.psafe3"
blocklist = [ "chess.com", "github.com" ]    #optional

[[scripts]]
dir = "./scripts"
blocklist = [ "live.com.js", "myaccount.google.com.js" ]   #optional

[urls]  #optional
"([^/]{1,30}://)?[^/]+@gmail.com$" = "myaccount.google.com"
"gmail.com" = "myaccount.google.com"
"youtube.com" = "myaccount.google.com"
"google.com" = "myaccount.google.com"
"skype.com/" = "live.com"
"(https://)?lichess.org(/([a-z]|[A-Z]|[0-9])*)*" = "lichess.org"
"non-domain-name-in-DB-file" = ""

[[scripts]]
dir = "development/my-custom-PassUp-scripts"